version: '3'

services:
  mongodb-container:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"

  memcached-container:
    image: memcached
    container_name: memcached-container
    ports:
      - "11211:11211"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: url-shortener-fastapi:latest
    ports:
      - "8000:8000"
    depends_on:
      - mongodb-container
      - memcached-container
